### ISSUE TITLE
jeayeson is broken after updating to boost 1.58.0

### ISSUE THREAD

**Issue by xu-cheng** [jeaye/jeayeson#14]
https://gist.github.com/xu-cheng/90bd80b17fe88f65dd2d

**Comment by jeaye** [comment]
Interesting! This is with the latest `master` branch? I'll test this locally to see if I can reproduce it.

**Comment by jeaye** [comment]
@xu-cheng I've pushed up a commit which has resolved the issue locally; all tests still pass properly. Let me know if you have any more problems.

**Comment by xu-cheng** [comment]
Thanks it fixes the problem for me.
