### ISSUE TITLE
Don't escape '/' automatically

### ISSUE THREAD

**Issue by jcelerier** [jeaye/jeayeson#15]
The JSON specification doesn't put '/' in the control character list (cf  http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf p.4) : the characters that must be escaped range from U+0000 to U+001F according to the spec and '/' is U+002F; escaping is possible but not mandatory for '/'.

Could it be possible to not automatically escape '/' ? When putting unix-y paths in json values, it's very cumbersome to read (`\/usr\/local\/lib`...).

**Comment by jeaye** [comment]
Hm, that seems reasonable to me. I'll put in a patch today with updated tests.

**Comment by jeaye** [comment]
@jcelerier Enjoy. I hope to push up some changes over the next couple of days, to the `nice_things` branch, which clean up the API. Keep an eye out for it in `master` soon.
