### ISSUE TITLE
make of test project (and my project) fails with error on the overloaded <<

### ISSUE THREAD

**Issue by yorkish** [jeaye/jeayeson#19]
See files with complete make output
[make-fail.txt](https://github.com/jeaye/jeayeson/files/680279/make-fail.txt)
[Makefile.txt](https://github.com/jeaye/jeayeson/files/680280/Makefile.txt)
[config.hpp.txt](https://github.com/jeaye/jeayeson/files/680281/config.hpp.txt)

jest has been installed with make install on my system
I'm running Fedora 25 with boost 1.60 and GCC version 6.2.1

**Comment by jeaye** [comment]
Thanks for reporting this! Looks like GCC 6.2.1 has changed its acceptance of friend declarations. This has been fixed and the build is passing on older compilers, too, says Travis.

**Comment by yorkish** [comment]
compiles like a charm now!

thanks for the fast support! 👍
